apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-backend.fastapiName" . }}
  labels:
    {{- include "python-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fastapi.replicas }}
  selector:
    matchLabels:
      {{- include "python-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "python-backend.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.fastapi.port | quote }}
        prometheus.io/path: {{ .Values.fastapi.metrics.path | quote }}
    spec:
      {{- if .Values.fastapi.initContainer.enabled }}
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            - sh
            - -c
            - |
              until nc -z -v -w 2 {{ include "python-backend.postgresqlName" . }} 5432; do
                echo "Waiting for Postgres..."
                sleep 2
              done
      {{- end }}
      containers:
        - name: fastapi
          image: {{ .Values.fastapi.image }}
          ports:
            - containerPort: {{ .Values.fastapi.port }}
          env:
           - name: DB_PASSWORD
         {{- if .Values.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: {{ .Values.postgresql.auth.secretKeys.userPasswordKey | quote }}
         {{- else }}
              value: {{ .Values.postgresql.auth.password | quote }}
         {{- end }}
           - name: DATABASE_URL
             value: {{ include "python-backend.databaseUrl" . | quote }}
          resources:
            {{- toYaml .Values.fastapi.resources | nindent 12 }}
