apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "python-backend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "python-backend.fastapiName" $ }}
                port:
                  number: {{ $.Values.fastapi.port }}
          {{- end }}
          - path: {{ .Values.ingress.grafana.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "python-backend.grafanaName" . }}
                port:
                  number: {{ .Values.ingress.grafana.port }}